language: python
python:
    - 3.6
    - 3.7
before_install:
    - pip install poetry
    - openssl aes-256-cbc -K $encrypted_9cc621798169_key -iv $encrypted_9cc621798169_iv -in secrets/static.tar.enc -out secrets/static.tar -d
    - tar xvf secrets/static.tar -C src/maho/modules/
    - openssl aes-256-cbc -K $encrypted_9cc621798169_key -iv $encrypted_9cc621798169_iv -in secrets/Logs.tar.enc -out secrets/Logs.tar -d
    - tar xvf secrets/Logs.tar -C src/maho/
install:
    - poetry install
script:
    - poetry run flake8 maho test
    - poetry run maho test