language: python
python: [3.6, 3.7]
addons:
    ssh_known_hosts: $RELEASE_SERVER
before_install:
    - pip install poetry
install:
    - poetry install
    - pip install codecov
script:
    - poetry run flake8 maho test
    - poetry run pytest --cov-report=xml:"$HOME/.cache/codecov/coverage.xml"
    - coverage report --fail-under=80
before_deploy:
    - openssl aes-256-cbc -K $encrypted_5baae3a36782_key -iv $encrypted_5baae3a36782_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa
deploy:
    provider: script
    skip_cleanup: true
    script: ssh -i /tmp/deploy_rsa $RELEASE_SERVER_USER@$RELEASE_SERVER "cd ~/maho-bot; docker-compose down; git pull; docker-compose build; docker-compose up -d"
    on:
        branch: master
after_success:
    - codecov -t "$CODECOV_TOKEN" -f "$HOME/.cache/codecov/coverage.xml"