version: "3"
services:
    maho:
        container_name: maho
        hostname: maho
        restart: unless-stopped
        image: maho
        build:
            context: .
        env_file:
            - .env
        environment:
            - BOT_DB=data/maho.db
        volumes:
            - ./data:/app/data
