#!/usr/bin/env python
import re
import subprocess
import runpy
from pathlib import Path
import shutil
import click
import inquirer


def stringify_list(values, process=None):
    """Function to change a python list into its string representation"""
    strings = [f'"{value}"' for value in values if value]
    if process:
        strings = [process(string) for string in strings]
    return f"[{', '.join(strings)}]"


@click.group()
def maho():
    """
    Command line tool to manage the bot.
    """
    pass


@maho.command()
@click.option(
    "--prefix", "-p", prompt="Prefix to use for bot commands", type=str, default="$"
)
@click.option(
    "--description", "-d", prompt="The bot's description text", type=str, default=""
)
@click.option("--token", "-t", prompt="The bot's access token", type=str)
@click.option("--admins", "-a", prompt="User IDs of Bot admins", type=str, default="")
@click.option(
    "--database", "-db", prompt="The database file to use", type=str, default="maho.db"
)
def init(prefix, description, token, admins, database):
    """Initialize the bot's configuration."""
    root_dir = Path(__file__).parent.parent

    ### Admin parsing
    admins = ";".join(re.split(r", |,| ", admins))

    ### Module prompt
    module_folder = root_dir / "src" / "maho" / "modules"
    all_modules = [
        file.stem
        for file in module_folder.glob("*.py")
        if not file.stem.startswith("__") and file.stem != "help"
    ]

    questions = [
        inquirer.Checkbox(
            "mods", message="Select the modules you want to load", choices=all_modules
        )
    ]
    answers = inquirer.prompt(questions)
    modules = ";".join([f"{module}" for module in answers["mods"]])

    questions = [
        inquirer.Checkbox(
            "startup_mods",
            message="Select the modules you want to load on startup",
            choices=answers["mods"],
        )
    ]
    answers = inquirer.prompt(questions)
    startup_modules = ";".join([f"{module}" for module in answers["startup_mods"]])

    ### Save into .env file
    dotenv = root_dir / ".env"
    with dotenv.open(mode="w") as f:
        f.writelines(
            [
                f"BOT_PREFIX={prefix}\n",
                f"BOT_TOKEN={token}\n",
                f"BOT_DESCRIPTION={description}\n",
                f"BOT_ADMINS={admins}\n",
                f"BOT_MODULES={modules}\n",
                f"BOT_STARTUP_MODULES={startup_modules}\n",
                f"BOT_DB={database}\n",
            ]
        )

    click.secho("Config initalized successfully.", fg="green")


@maho.command()
def test():
    subprocess.run("pytest")


@maho.command()
def run():
    runpy.run_module("maho.main", run_name="__main__")


if __name__ == "__main__":
    maho()
